version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_RUN_HOST: ${FLASK_RUN_HOST}
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}